#!/bin/bash
#
# chkconfig: 2345 89 26
# description: mios_agent
# probe: false

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up. If you are running without a network, comment this out.
[ "${NETWORKING}" = "no" ] && exit 0

RETVAL=0
MAGENT_HOME="/opt/mios/mios-agent/"
prog="mios-agent"

start() {
        # Start daemons.
	echo -n $"Starting $prog: "
	${MAGENT_HOME}bin/$prog start
	RETVAL=$?
	[ $RETVAL -ne 0 ] && failure $"$prog startup"
	[ $RETVAL -eq 0 ] && success $"$prog startup"
        echo
        return $RETVAL
}
stop() {
        # Stop daemons.
        echo -n $"Stopping $prog: "
	${MAGENT_HOME}bin/$prog stop
        RETVAL=$?
        [ $RETVAL -ne 0 ] && failure $"$prog stop"
        [ $RETVAL -eq 0 ] && success $"$prog stop"
        echo
        return $RETVAL
}
restart() {
	${MAGENT_HOME}bin/$prog restart
}

# See how we were called.
case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                restart
                ;;
        *)
                echo $"Usage: $0 {start|stop|restart}"
                exit 1
esac

exit $?

