#!/bin/bash
#
# chkconfig: 2345 89 26
# description: mios_agent
# probe: false

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up. If you are running without a network, comment this out.
[ "${NETWORKING}" = "no" ] && exit 0
pidfile='/var/run/mios/mios-agent.pid'
RETVAL=0
user=`whoami`
start() {
        # Start daemons.
	echo -n $"Starting $0: "
	case "$user" in
		"mios")
			${MAGENT_HOME}/bin/mios-agent start
			RETVAL=$?
			;;
		"root")
			runuser -l mios -c '${MAGENT_HOME}/bin/mios-agent start'
			RETVAL=$?
			;;
		*)
			echo "Cannot run as this user"
			RETVAL=1
			;;
	esac
	[ $RETVAL -ne 0 ] && failure $"$0 startup"
	[ $RETVAL -eq 0 ] && success $"$0 startup"
        echo
        return $RETVAL
}
stop() {
        # Stop daemons.
        echo -n $"Stopping $0: "
	case "$user" in
		"mios")
			${MAGENT_HOME}/bin/mios-agent stop
			RETVAL=$?
			;;
		"root")
			runuser -l mios -c '${MAGENT_HOME}/bin/mios-agent stop'
			RETVAL=$?
			;;
		*)
			echo "Cannot run as this user"
			RETVAL=1
			;;
	esac
        [ $RETVAL -ne 0 ] && failure $"$0 stop"
        [ $RETVAL -eq 0 ] && success $"$0 stop"
        echo
        return $RETVAL
}
restart() {
	stop
	sleep 3
	start
}

# See how we were called.
case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
	status)
		status -p ${pidfile} mios-agent
		RETVAL=$?
		;;
        restart)
                restart
                ;;
        *)
                echo $"Usage: $0 {start|stop|status|restart}"
                exit 1
esac

exit $?

