#!/bin/bash
#
# chkconfig: 2345 89 26
# description: mios_agent
# probe: false

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up. If you are running without a network, comment this out.
[ "${NETWORKING}" = "no" ] && exit 0

RETVAL=0

start() {
        # Start daemons.
	echo -n $"Starting $0: "
	runuser -l mios -c '${MAGENT_HOME}/bin/mios-agent start'
	RETVAL=$?
	[ $RETVAL -ne 0 ] && failure $"$0 startup"
	[ $RETVAL -eq 0 ] && success $"$0 startup"
        echo
        return $RETVAL
}
stop() {
        # Stop daemons.
        echo -n $"Stopping $0: "
	runuser -l mios -c '${MAGENT_HOME}/bin/mios-agent stop'
        RETVAL=$?
        [ $RETVAL -ne 0 ] && failure $"$0 stop"
        [ $RETVAL -eq 0 ] && success $"$0 stop"
        echo
        return $RETVAL
}
restart() {
	stop
	sleep 3
	start
}

# See how we were called.
case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                restart
                ;;
        *)
                echo $"Usage: $0 {start|stop|restart}"
                exit 1
esac

exit $?

